[package]
name = "paat"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix = "0.12"
reqwest = "0.11"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
