name: Paat Build Workflow
on:
  push:
    branches:
      - master
jobs:
  windows_x86_64:
    name: Windows 64bit build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-pc-windows-gnu	
          override: true
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --target x86_64-pc-windows-gnu --release
      - uses: actions/upload-artifact@v2
        with: 
          name: deputy-cli
          path: target/x86_64-pc-windows-gnu/release
  linux_x86_64:
    name: Linux 64bit build
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-unknown-linux-gnu
          override: true
      - name: Install xmllint
        run: sudo apt-get install -y libasound2-dev
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --target x86_64-unknown-linux-gnu	--release
      - uses: actions/upload-artifact@v2
        with: 
          name: deputy-cli
          path: target/x86_64-unknown-linux-gnu/release
  mac_x86_64:
    name: Mac 64bit build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-apple-darwin
          override: true
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --target x86_64-apple-darwin --release
      - uses: actions/upload-artifact@v2
        with: 
          name: deputy-cli
          path: target/x86_64-apple-darwin/release
