name: Release paat-cli
on:
  push:
    tags:        
      - paat-cli.v*
jobs:
  windows_x86_64:
    name: Windows 64bit build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-pc-windows-gnu	
          override: true
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --target x86_64-pc-windows-gnu --release
      - name: Rename executable
        run: mv target/x86_64-pc-windows-gnu/release/paat-cli.exe target/x86_64-pc-windows-gnu/release/paat-cli_x86_64.exe
      - uses: softprops/action-gh-release@v1
        with:
          files: |
            target/x86_64-pc-windows-gnu/release/paat-cli_x86_64.exe
  linux_x86_64:
    name: Linux 64bit build
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-unknown-linux-gnu
          override: true
      - name: Install xmllint
        run: sudo apt-get install -y libasound2-dev
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --target x86_64-unknown-linux-gnu	--release
      - name: Rename executable
        run: mv target/x86_64-unknown-linux-gnu/release/paat-cli target/x86_64-unknown-linux-gnu/release/paat-cli-linux64
      - uses: softprops/action-gh-release@v1
        with:
          files: |
            target/x86_64-unknown-linux-gnu/release/paat-cli-linux64
  mac_x86_64:
    name: Mac 64bit build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-apple-darwin
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --target x86_64-apple-darwin --release
      - name: Rename executable
        run: mv target/x86_64-apple-darwin/release/paat-cli target/x86_64-apple-darwin/release/paat-cli-macos_x86_64
      - uses: softprops/action-gh-release@v1
        with:
          files: |
            target/x86_64-apple-darwin/release/paat-cli-macos_x86_64
